### ISSUE TITLE
ERROR When Running On server(PaperSpigot,1.8.8)

### ISSUE THREAD

**Issue by sheip9** [pavog/craftconomy3#104]
[19:14:51 WARN]: Exception in thread "Craft Scheduler Thread - 48" 
[19:14:51 WARN]: org.apache.commons.lang.UnhandledException: Plugin PlaceholderAPI v2.10.4 generated an exception while executing task 56
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:823)
Caused by: java.lang.NullPointerException
        at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.getBalance(Economy_Craftconomy3.java:279)
        at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.getBalance(Economy_Craftconomy3.java:121)
        at net.milkbowl.vault.economy.AbstractEconomy.getBalance(AbstractEconomy.java:22)
        at com.extendedclip.papi.expansion.vault.VaultEcoHook.getBalance(VaultEcoHook.java:220)
        at com.extendedclip.papi.expansion.vault.BalTopTask.run(BalTopTask.java:48)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
[19:14:51 WARN]: Exception in thread "Craft Scheduler Thread - 48" 
[19:14:51 WARN]: org.apache.commons.lang.UnhandledException: Plugin PlaceholderAPI v2.10.4 generated an exception while executing task 56
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:823)
Caused by: java.lang.NullPointerException
        at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.getBalance(Economy_Craftconomy3.java:279)
        at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.getBalance(Economy_Craftconomy3.java:121)
        at net.milkbowl.vault.economy.AbstractEconomy.getBalance(AbstractEconomy.java:22)
        at com.extendedclip.papi.expansion.vault.VaultEcoHook.getBalance(VaultEcoHook.java:220)
        at com.extendedclip.papi.expansion.vault.BalTopTask.run(BalTopTask.java:48)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

**Comment by pavog** [comment]
Hi @sheip9 and thanks for reporting this issue.
It seems like this error occurs when a player does not have an account in craftconomy but the placeholder api requests the balance.
Can you please check that for me?

**Comment by sheip9** [comment]
I solved it by myself. :D I check all service again and found out that it caused by the problem of connection between mysqld and minecraft server. Thanks ur reply.

**Comment by pavog** [comment]
Hi, I have released a new Craftconomy version 3.5.4 which should fix the problem with newer Paper versions.
