### ISSUE TITLE
Duplicate entry error

### ISSUE THREAD

**Issue by netherstar** [pavog/craftconomy3#56]
craftconomy latest version download from here: https://github.com/pavog/craftconomy3/releases/latest
PaperSpigot 1.12.2
```
[07:23:54] [Server thread/WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'd369fae3-43ed-312b-b3a8-bf66ee5d888a' for key 'uuid'
[07:23:54] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[07:23:54] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[07:23:54] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[07:23:54] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[07:23:54] [Server thread/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[07:23:54] [Server thread/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:408)
[07:23:54] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
[07:23:54] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
[07:23:54] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
[07:23:54] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
[07:23:54] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
[07:23:54] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
[07:23:54] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
[07:23:54] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
[07:23:54] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
[07:23:54] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
[07:23:54] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
[07:23:54] [Server thread/WARN]: 	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
[07:23:54] [Server thread/WARN]: 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
[07:23:54] [Server thread/WARN]: 	at com.greatmancode.craftconomy3.storage.sql.SQLStorageEngine.getAccount(SQLStorageEngine.java:101)
[07:23:54] [Server thread/WARN]: 	at com.greatmancode.craftconomy3.storage.StorageEngine.getAccount(StorageEngine.java:56)
[07:23:54] [Server thread/WARN]: 	at com.greatmancode.craftconomy3.account.AccountManager.getAccount(AccountManager.java:56)
[07:23:54] [Server thread/WARN]: 	at com.greatmancode.craftconomy3.events.EventManager.playerJoinEvent(EventManager.java:47)
[07:23:54] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor118.invoke(Unknown Source)
[07:23:54] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[07:23:54] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[07:23:54] [Server thread/WARN]: 	at com.greatmancode.tools.events.ListenerRegistration.callEvent(ListenerRegistration.java:40)
[07:23:54] [Server thread/WARN]: 	at com.greatmancode.tools.events.EventManager.callEvent(EventManager.java:59)
[07:23:54] [Server thread/WARN]: 	at com.greatmancode.tools.events.bukkit.PlayerJoinEventListener.onPlayerJoin(PlayerJoinEventListener.java:43)
[07:23:54] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor117.invoke(Unknown Source)
[07:23:54] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[07:23:54] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[07:23:54] [Server thread/WARN]: 	at com.massivecraft.massivelag.inject.MassiveLagEventExecutor.execute(MassiveLagEventExecutor.java:69)
[07:23:54] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[07:23:54] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)
[07:23:54] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:370)
[07:23:54] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:183)
[07:23:54] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:178)
[07:23:54] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:68)
[07:23:54] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:273)
[07:23:54] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:150)
[07:23:54] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:948)
[07:23:54] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[07:23:54] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[07:23:54] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[07:23:54] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[07:23:54] [Server thread/INFO]: datcop[/117.3.101.77:38549] logged in with entity id 325 at ([hub]0.4160261792379757, 28.0625, 28.904079646505743)
[07:23:54] [Server thread/WARN]: org.bukkit.command.CommandException: Unhandled exception executing command 'money' in plugin Craftconomy3 v3.5.1-SNAPSHOT
[07:23:54] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
[07:23:54] [Server thread/WARN]: 	at com.massivecraft.massivelag.inject.MassiveLagCommandMap.dispatch(MassiveLagCommandMap.java:98)
[07:23:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
[07:23:54] [Server thread/WARN]: 	at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:607)
[07:23:54] [Server thread/WARN]: 	at ch.njol.skript.Skript.dispatchCommand(Skript.java:1188)
[07:23:54] [Server thread/WARN]: 	at ch.njol.skript.effects.EffCommand.execute(EffCommand.java:84)
[07:23:54] [Server thread/WARN]: 	at ch.njol.skript.lang.Effect.run(Effect.java:52)
[07:23:54] [Server thread/WARN]: 	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[07:23:54] [Server thread/WARN]: 	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[07:23:54] [Server thread/WARN]: 	at ch.njol.skript.effects.Delay$1.run(Delay.java:101)
[07:23:54] [Server thread/WARN]: 	at com.massivecraft.massivelag.inject.MassiveLagRunnable.run(MassiveLagRunnable.java:56)
[07:23:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
[07:23:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423)
[07:23:54] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840)
[07:23:54] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[07:23:54] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[07:23:54] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[07:23:54] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[07:23:54] [Server thread/WARN]: Caused by: java.lang.NullPointerException
[07:23:54] [Server thread/WARN]: 	at com.greatmancode.craftconomy3.commands.money.SetCommand.execute(SetCommand.java:55)
[07:23:54] [Server thread/WARN]: 	at com.greatmancode.tools.commands.SubCommand.execute(SubCommand.java:73)
[07:23:54] [Server thread/WARN]: 	at com.greatmancode.tools.commands.bukkit.BukkitCommandReceiver.onCommand(BukkitCommandReceiver.java:61)
[07:23:54] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[07:23:54] [Server thread/WARN]: 	... 17 more
```

**Comment by pavog** [comment]
Thank you for reporting this issue. I will look into it asap and ping you once I made any progress on it.

**Comment by netherstar** [comment]
@pavog 
Unexpected exception when tried to run money command on console
https://paste.ubuntu.com/p/VThTbdsKKM/
other suggest: i known there option SilentGiveCommand: true in config, but it's only silent for console and only give command,  can you make silent option for other commands and even silent for player?
for example:
/money -s give/take/set will silent on console
/money -S give/take/set will silent for both console and player (who received money)

Sorry for bad english

**Comment by netherstar** [comment]
And how to disable vault integrate?

**Comment by pavog** [comment]
Thanks for your second bug report and the suggestion to add the silent flag.

Can you give me any private contact information (discord, email, skype, ...) so I can fix the bugs with you and help with your other problems / questions?

**Comment by netherstar** [comment]
> Thanks for your second bug report and the suggestion to add the silent flag.
> 
> Can you give me any private contact information (discord, email, skype, ...) so I can fix the bugs with you and help with your other problems / questions?

sure, my discord LapizSeller#6359
